### ISSUE TITLE
Question 7

### ISSUE THREAD

**Issue by cschmer** [jmbejara/comp-econ-sp19#11]
![Screen Shot 2019-04-15 at 7 07 21 PM](https://user-images.githubusercontent.com/39018665/56173078-c924e800-5fb1-11e9-8554-98bc78ee80b5.png)
![Screen Shot 2019-04-15 at 7 07 19 PM](https://user-images.githubusercontent.com/39018665/56173079-c9bd7e80-5fb1-11e9-943a-549f95e227b7.png)

For question 7 (analytical), I get this graph... This may be because I put the initial weight to w0. How should I resolve this or do something about this, or is this correct?

**Comment by cschmer** [comment]
It is not correct since I get False for the following question... may somebody help me? 

I do not have any lambdas for functions. Do I need those? The only local variables I have are those that define parts of the equation (like A, or [mu, identity])

**Comment by cschmer** [comment]
Fixed! 

If anyone has a similar problem (Hopefully not), I did w0 @ mu instead of mu_target in my verticle stack of mu_p and 1.

**Comment by jmbejara** [comment]
Glad it worked! Just to add to the discussion, 
![image](https://user-images.githubusercontent.com/3770323/56178095-91746b00-5fc6-11e9-8ee0-c49cbc25f22b.png)
gives the relationship between a given `mu_p` and `wstar`. We can then use that weight vector `wstar` to calculate portfolio variance, `wstar.T @ Sigma @wstar`. The composition of these two functions gives us the relationship between `mu_p` and the minimal variance.
