### ISSUE TITLE
Separate Notebooks for HW2?

### ISSUE THREAD

**Issue by jonhelium** [jmbejara/comp-econ-sp19#12]
Since there are 3 different notebooks we reference for HW2, do we need to submit a different notebook corresponding to each one? Or is it alright if we submit a singular notebook that combines the 3?

**Comment by jmbejara** [comment]
Hi @jonhelium . It's ok if you submit a single notebook that contains all parts. I split them up because I thought it would be more convenient to keep them separate. If you like them combined, that's ok too.
