### ISSUE TITLE
HW 2, chipotle (# 19)

### ISSUE THREAD

**Issue by henryli78** [jmbejara/comp-econ-sp19#13]
The question statement is: 

> 19. Select and return the rows corresponding to the Barbacoa Bowl. Give two reasons why the item price might vary. 

I gave the answer 

> One reason for the price variation is that different bowls have different choices, and hence, have different final costs depending on the alterations. 

> Another reason is that there could be multiple Barbacoa Bowls ordered at once (in the same order), so item price would be larger.

However, I wanted to make sure that this is a legitimate claim (specifically the multiple Barbacoa Bowls part). Using 

`chipo[chipo['item_name'] == 'Barbacoa Bowl']['quantity'].unique()`

I get output 

`array([1])`

Which implies that all quantities are 1. So is my answer still legit? It doesn't seem supported by our data set but I can't think of any other possible reason for this, other than heterogeneity of stores (there are 2 stores in our sample, but there is no data on the stores' individually pricing itself).

Thanks!

**Comment by jmbejara** [comment]
Yeah, I think your answer is correct. You're right, it looks like the Barbacoa Bowl doesn't seem to have any cases of quantities varying from 1. However, it looks like there is this kind of variation with Chicken Bowls.

![image](https://user-images.githubusercontent.com/3770323/56409292-09989600-623e-11e9-9a8e-3786c61e0175.png)




Also, just FYI, the `query` method is a nice, readable function that I like. You may have used it before. In case not, here's an example. These two things are equivalent:

```python
chipo[chipo['item_name'] == 'Barbacoa Bowl']
# same as
chipo.query("item_name == 'Barbacoa Bowl'")
```

https://jakevdp.github.io/PythonDataScienceHandbook/03.12-performance-eval-and-query.html#DataFrame.query()-Method
