### ISSUE TITLE
Monte Carlo graphing error

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#15]
Hey, I have been trying to debug this for a bit and am confused as to why it is throwing an error. Unless I am missing something, this is the same code as with the lecture notebooks for running/displaying results at different sizes of N. Yet when I try to display it with the seaborn library it gives: 

ValueError: color kwarg must have one color per data set. 1000 data sets and 1 colors were provided

The type of results.x1 is a series, which seems right. Any ideas?

<img width="674" alt="sim" src="https://user-images.githubusercontent.com/32854361/56432735-2495f500-6294-11e9-8f30-4f06f2e778ab.PNG">

**Comment by jmbejara** [comment]
Hmm. I'm not sure why this is happening. My first thought was that it maybe had something to do with the fact that you're running this on Colab. However, I just tried to run the Monte Carlo lecture on GitHub and it seems to work fine. 

Yeah, `results.x1` should be a Series.

I think it would help to see your `import` statements at the beginning. It would also be helpful if you could produce a ["minimal working example"](https://en.wikipedia.org/wiki/Minimal_working_example) that reproduces the bug.

**Comment by rhuselid** [comment]
Here are my imports:

<img width="858" alt="imports" src="https://user-images.githubusercontent.com/32854361/56434559-b3a60b80-629a-11e9-965f-0df63bf5cb44.PNG">

**Comment by jmbejara** [comment]
Hmm. Ok. Yeah, that's weird. I can't see any issues. Try creating a minimal working example that replicates the bug. Then post that example. If you aren't able to do that, email me your code (or come to Ari's office hours on Monday morning).

**Comment by rhuselid** [comment]
Turns out I made a small typo: results instead of results1, which caused the error
