### ISSUE TITLE
HW2 Creating Reading Writing Q7

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#19]
I'm having trouble working with the question 7 in creating reading writing section of HW2. After I downloaded the data, I can't release the file into csv, and below is the code I got. 
![Screen Shot 2019-04-20 at 10 43 31 PM](https://user-images.githubusercontent.com/49537572/56464953-25c54000-63c2-11e9-8012-3ccba3e59300.png)

**Comment by jmbejara** [comment]
That seems correct to me so far. Can you copy the rest of the error message?

**Comment by sicelyli** [comment]
Here's the complete error message:
![Screen Shot 2019-04-21 at 7 43 15 PM](https://user-images.githubusercontent.com/49537572/56477663-c886c880-646d-11e9-984c-7568f247515e.png)
![Screen Shot 2019-04-21 at 7 42 55 PM](https://user-images.githubusercontent.com/49537572/56477665-c91f5f00-646d-11e9-907c-f12c6a9bc270.png)

**Comment by jmbejara** [comment]
Weird. The only thing that I can imagine is that you have the wrong data set downloaded. Try to download it again and make sure that it's in the right folder. To run your code as written, put the file in the location that the Python interpreter is running. To find out what folder this is, run `%pwd` in your notebook. Let me know if this helps!
