### ISSUE TITLE
Midterm solutions type error

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#23]
I was working through last year's midterm and I ran into bug where I got a type error whenever I tried to use pivot tables. When I ran the given solutions, I got the same error:

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

This was from question 6 and 8 from last year's midterm. I am running this on jupyter notebook

**Comment by rhuselid** [comment]
Update: when I ran the solution in colab I had the same error.

**Comment by jmbejara** [comment]
Hi. Thanks for finding this. It seems that there is an issue with `pivot_table` using Categorical variables. This wasn't a problem last year. You can fix this by changing the "loading" code to the following:

```python
euro12 = pd.read_csv('https://raw.githubusercontent.com/jokecamp/FootballData/master/UEFA_European_Championship/Euro%202012/Euro%202012%20stats%20TEAM.csv', sep=',')
euro12['Shooting Accuracy'] = euro12['Shooting Accuracy'].str[:-1].astype(float)
quartiles = [0, .25, .5, .75, 1.]
labels = ['Q1', 'Q2', 'Q3', 'Q4']
# labels = None
euro12['passes_quartile'] = pd.qcut(euro12['Passes'], q=quartiles, labels=labels)
euro12['shoot_acc_quartile'] = pd.qcut(euro12['Shooting Accuracy'], q=quartiles, labels=labels)
euro12.dtypes

```

That is, use the quartile labels that were given. Thanks!
