### ISSUE TITLE
HW 3-Productivity&Monte Carlo-Q6

### ISSUE THREAD

**Issue by cangubur** [jmbejara/comp-econ-sp19#28]
We are given to use M=100, but you haven't mentioned any specifications on N and T to use with  gen_all to create different data. Should we go ahead and continue to use gen_all(N=3,T=50) as in previous examples or should we loop over gen_all(N=1,T=1) 100 times?

**Comment by jmbejara** [comment]
Sorry about that. If it doesn't say otherwise, just stick with the defaults. Thanks!
