### ISSUE TITLE
Can we set up our git, etc on VM?

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#3]
For students coming from the CS 120s, can we simply clone the repository we create into our virtual machine? I am used to dealing with git from the command line in a linux environment so that may be easier for me plus I already have all the packages/ipython3 installed there.

Thanks!

**Comment by jmbejara** [comment]
Hi @rhuselid . That would be absolutely great! For the first week, I'm encouraging those that are new to Git and GitHub to submit their HW, etc the easy way (direct upload). However, I would eventually like everyone to learn how to properly use a Git client, as you suggest (clone, commit, push, etc.).

**Comment by jmbejara** [comment]
Though, I'm not sure what kind of VM you're using. The VM is not necessarily essential to the Git workflow, but you may use one if you would like.

**Comment by rhuselid** [comment]
Great, thanks!
