### ISSUE TITLE
HW 3 Productivity: Plotting a df with multi-index

### ISSUE THREAD

**Issue by henryli78** [jmbejara/comp-econ-sp19#30]
Hi! I'm trying to do Q3-Q5 on HW3's productivity section. I'm right now doing something that I feel is inefficient, i.e.:

`df['y'].loc[0].plot()`
`df['y'].loc[1].plot()`
`df['y'].loc[2].plot()`

but my issue is that this seems really inefficient. Is there some better way of doing this? I tried to read through the help for the df.plot() function [here](https://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.DataFrame.plot.html) but it didn't seem to help me too much. 

Thanks!

**Comment by jmbejara** [comment]
You can just use `matplotlib.pyplot` and give it multiple rows. I did it like this:

![image](https://user-images.githubusercontent.com/3770323/56915222-95e75c00-6a7b-11e9-93f2-4e10e4a2f5ce.png)

**Comment by jmbejara** [comment]
Another option is to use a "for-loop." Yet another option, using the DataFrame, is this:

```python
df['y'].unstack().T.plot()
```

![image](https://user-images.githubusercontent.com/3770323/56915715-d693a500-6a7c-11e9-8231-94f02aa29b85.png)

**Comment by henryli78** [comment]
Thank you! This works very well.
