### ISSUE TITLE
Downloading a CSV from IPUMS

### ISSUE THREAD

**Issue by jbendelac** [jmbejara/comp-econ-sp19#31]
Hello,

I downloaded the dataset from IPUMS but I seem to only be able to download the file as a .dat. How do I download it as a csv instead? Thanks!

**Comment by jmbejara** [comment]
Hi @jbendelac . When you are submitting your extract request, you should see an option to change the data format. See here:

![image](https://user-images.githubusercontent.com/3770323/57005020-d0471b00-6b99-11e9-9dde-6277c51efb70.png)

and here:

![image](https://user-images.githubusercontent.com/3770323/57005005-b7d70080-6b99-11e9-8fe2-218fe64dea8c.png)

**Comment by jbendelac** [comment]
Thanks!
