### ISSUE TITLE
Data selection HW#4

### ISSUE THREAD

**Issue by richard-archer** [jmbejara/comp-econ-sp19#36]
My df.info() is largely the same as yours, but the file size is twice as large and WKSWORK1, UHRSWORKLY, INCWAGE are floats instead of ints. My guess is that I selected too much data from IPUMS - is something wrong with my selection?

![image](https://user-images.githubusercontent.com/49219723/57182530-afb2e580-6e65-11e9-83c2-d1b4649d5855.png)

![image](https://user-images.githubusercontent.com/49219723/57182543-bb061100-6e65-11e9-8340-7e539c0627ee.png)

![image](https://user-images.githubusercontent.com/49219723/57182450-d15f9d00-6e64-11e9-8d42-2b9ebc49c559.png)

**Comment by richard-archer** [comment]
Edit - I altered the selection to only include March for the relevant years but still have the incorrect file size

![image](https://user-images.githubusercontent.com/49219723/57182783-0e2d9300-6e69-11e9-9f32-0b3851a12834.png)

**Comment by richard-archer** [comment]
Sorry, issue resolved - shouldn't have selected the individual months

**Comment by jmbejara** [comment]
Glad you were able to fix it!
