### ISSUE TITLE
Slightly different counts

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#39]
I am dropping too many observations in my dataframe during the Q3 recording portion, which I think is throwing my values slightly off for the rest of the HW. Bellow is how I recoded data--is it different than how you did it?

<img width="770" alt="recoding" src="https://user-images.githubusercontent.com/32854361/57195476-afbfed80-6f18-11e9-9ec3-6f3173e37235.PNG">

**Comment by jmbejara** [comment]
I don't treat 99 as missing in the `UHRSWORKLY` series, though they should indeed be treated as special.
