### ISSUE TITLE
Convert int64 to datetime64-HW4

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#40]
I'm having trouble converting the year column into datetime64[ns]
I tried to_datetime couple times setting the unit differently, but seems like all of them set the year to 1970
![Screen Shot 2019-05-05 at 11 53 09 PM](https://user-images.githubusercontent.com/49537572/57207218-79728480-6f91-11e9-9483-e85e353a36da.png)
![Screen Shot 2019-05-05 at 11 53 17 PM](https://user-images.githubusercontent.com/49537572/57207221-7b3c4800-6f91-11e9-8af1-3ff87620036b.png)

**Comment by jmbejara** [comment]
Take a look at the documentation for `pd.to_datetime`.  https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html
```
format : string, default None
    strftime to parse time, eg “%d/%m/%Y”, note that “%f” will parse all the way up to nanoseconds.
```

There are multiple ways to do this. One way is to use the `format` keyword argument. This accepts strings with symbols according to this reference: http://strftime.org/

**Comment by sicelyli** [comment]
Got it, thank you!
