### ISSUE TITLE
HW4 Q6 Real_Wages

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#41]
When I'm comparing my df.describe with the one provided in the question, all other columns are correct except the "real_wage" column. I think there could be an issue with the way I set up the real wage column, but I'm not really sure what the problem is.
![Screen Shot 2019-05-06 at 12 09 47 AM](https://user-images.githubusercontent.com/49537572/57207474-99a34300-6f93-11e9-9a02-9d9159df3563.png)
![Screen Shot 2019-05-06 at 12 10 00 AM](https://user-images.githubusercontent.com/49537572/57207476-9a3bd980-6f93-11e9-83f3-5a27782704b1.png)

**Comment by jmbejara** [comment]
You're not correcting for inflation when you calculate `real_wage`.

**Comment by sicelyli** [comment]
I just changed the numerator from "INCWAGE" to "real_incwage" and it works. Thank you!
