### ISSUE TITLE
error reading df hw6

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#48]
When I run this code from the HW:
```
url = 'https://raw.githubusercontent.com/jmbejara/comp-econ-sp18/master/lectures/5-08_Structural_IO_with_MLE/'
filename = 'BresnahanAndReiss1991_DATA.csv'
df = pd.read_csv(url + filename)
```

I get a HTTPError: HTTP Error 404: Not Found error. What should the url be instead?

**Comment by rhuselid** [comment]
Update: the url just has to be replaced with the url from lecture notes. I did not initially notice that they were a little different

**Comment by jmbejara** [comment]
Cool. Glad it got resolved! Opening this in case others have the same issue.
