### ISSUE TITLE
Hw 6 Replication Question

### ISSUE THREAD

**Issue by jbendelac** [jmbejara/comp-econ-sp19#49]
Hello, I'm slightly confused about the definitions of variables in the data. Can we find Z and W in the data, and what variables represent them? Also in the definition of F_N in the writeup, what exactly does W_L represent? I'm confused what the L subscript means. Thanks!

**Comment by jmbejara** [comment]
Hi. Good question! The variables used in Z and W are in the paper. Specifically, you can infer them from Table 4. You can also find W_L on p. 992 and also in Table 4.
