### ISSUE TITLE
Average profits for different N

### ISSUE THREAD

**Issue by cangubur** [jmbejara/comp-econ-sp19#51]
When we talked about what would be an easy way to approach Q1, you said find the average profits for N=0 to 6, but isn't that wrong?

Since different markets (counties) have different populations and different population variables, shouldn't we just loop through every row and calculate profits for each county and etc.

**Comment by jmbejara** [comment]
We must have had a miscommunication. What you describe would indeed be wrong. I think I was discussing two different approaches you could take when you code up the log-likelihood function: you could write a "for"-loop through each observation. Or you could [vectorize](https://stackoverflow.com/questions/47755442/what-is-vectorization) some of the operations. For example, give parameters `theta`, you could compute S,V, and F for each row in single, vectorized operations.
