### ISSUE TITLE
Q5-Q6 Replication

### ISSUE THREAD

**Issue by jbendelac** [jmbejara/comp-econ-sp19#55]
Hi, I'm confused about the notation in the paper for Table 5, where there are both capital and lower case S's ( It's clear from the table that S2/S1 does not equal s1/s2). What is the difference between the two, and how do I calculate s1-s5? I can't tell from the paper what the difference is.

**Comment by jmbejara** [comment]
Hi. No problem! The lowercase is the per-firm threshold. It's below equation (4) in the class lecture and here in the paper:

![image](https://user-images.githubusercontent.com/3770323/57974665-b8390f00-7981-11e9-8b44-3b990612e2d0.png)

**Comment by erineidschun** [comment]
How do we create a table once we've calculated the values? There are many methods online and none of them compile for me.

**Comment by jmbejara** [comment]
@erineidschun I was thinking that you would just put them into their own pandas.DataFrame in a presentable fashion. 

This doesn't exactly apply here, but just to note, DataFrame's have methods called (`DataFrame.to_latex`)[https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_latex.html] and `DataFrame.to_html`, if that's useful to you.
