### ISSUE TITLE
slighly different values for Q5,6

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#57]
Hi! I am getting fairly close results to those in the paper for the graph and df, but they seem to differ by a small, but persistent difference. I think that my error is either in how I am setting up X bar or how I am adding coefficents if N is sufficiently large;. 

If you have time could you point out what is the error I am making here? I have been looking at it for a while and am missing it. Thanks!

```
def break_points(df, gamma, alpha, beta, N):
    Z = np.c_[df.ELD.mean(), df.PINC.mean(), df.LNHDD.mean(), df.FFRAC.mean()]  #X bar
    W = df.LANDV.mean() # gammaL mean
    X = np.c_[Z]
    
    base_numerand = gamma[0] + gamma[5]*W
    base_denominator = alpha[0] + X@beta
    
    num_add = []
    den_sub = []
    
    for i in range(1, N):
        num_add += [gamma[i]]
        den_sub += [alpha[i]]

    rv = (base_numerand + sum(num_add)) / (base_denominator - sum(den_sub))
    return rv
```

For reference here is my return:
<img width="359" alt="lnl" src="https://user-images.githubusercontent.com/32854361/57976960-999f3c00-79b2-11e9-8953-e4ce96d75d1d.PNG">

Vs the paper:
<img width="1081" alt="nkn" src="https://user-images.githubusercontent.com/32854361/57976964-b6d40a80-79b2-11e9-9076-90cb7f755a77.PNG">

**Comment by jmbejara** [comment]
Cool. Yeah, those are really close. Mine don't match the paper perfectly either. Your and mine seem close enough that it wouldn't change the results at all. I wouldn't worry about it. Could be rounding error at some point. I'm not sure.

This is what I'm getting:

![image](https://user-images.githubusercontent.com/3770323/57988415-96a85800-7a53-11e9-934d-b49403697627.png)

**Comment by rhuselid** [comment]
Thanks!
