### ISSUE TITLE
Dealing with NaN Values

### ISSUE THREAD

**Issue by IshaanW** [jmbejara/comp-econ-sp19#59]
I'm working on Q1 and am generating lots of NaN values for the log-probabilities because of near-zero and negative probabilities (see the log-probabilities array in the attached picture). I'm wondering if this indicates a problem with my earlier code or if I just have to deal with these values in a similar way to the -inf values generated by np.log

<img width="721" alt="Screen Shot 2019-05-19 at 8 29 46 PM" src="https://user-images.githubusercontent.com/49291208/57991497-f06d4a00-7a74-11e9-8346-f8fb990717ef.png">

**Comment by jmbejara** [comment]
Hi! Something is definitely going wrong. log probabilities should be negative, by definition. (log of a number between zero and one (non-inclusive), should be a negative real number.

**Comment by IshaanW** [comment]
These are the values I'm getting for profit_bar for each N.

<img width="707" alt="Screen Shot 2019-05-20 at 10 30 17 AM" src="https://user-images.githubusercontent.com/49291208/58033533-44664600-7aea-11e9-9f17-b5b2028b8351.png">

I'm a little confused by what they mean - is the value calculated using equation (8) total profits for the N firms in a market or is it the market entry threshold. My numbers don't seem to follow the assumption below:

<img width="166" alt="Screen Shot 2019-05-20 at 10 32 43 AM" src="https://user-images.githubusercontent.com/49291208/58033723-9d35de80-7aea-11e9-8fef-feebd9c6702e.png">

Is there an additional step to take like dividing by the number of firms in the market or finding marginal profits (i.e., subtracting pi_(n-1) from pi_n)?

**Comment by IshaanW** [comment]
Never mind, I figured out the fundamental flaw in my understanding of the paper!
