### ISSUE TITLE
Hw 1 Q5 plotting several images using for loop

### ISSUE THREAD

**Issue by cangubur** [jmbejara/comp-econ-sp19#6]
I am trying to plot the requested images using a for loop and I can print everything except the last one. My code is: 

values = [500,300,100,50,10]
for i in values:
    plt.imshow(compress(face,i), cmap=plt.cm.gray)
    plt.figure(i)
plt.plot()

why can't I print the last image?

**Comment by cangubur** [comment]
If anyone has the same issue this works:

values = [500,300,100,50,10]
for v in values:
    plt.imshow(compress(face,v), cmap=plt.cm.gray)
    plt.figure(v)

**Comment by jmbejara** [comment]
Great post. In your first example, maybe rearranging like this would work:

```python
values = [500,300,100,50,10]
for i in values:
    plt.figure(i)
    plt.imshow(compress(face,i), cmap=plt.cm.gray)
```

`plt.figure()` creates a new figure. Here's a generic example:

```python
import numpy as np
from matplotlib import pyplot as plt

for n in range(5):
    x = np.linspace(0, (n+1) * np.pi,100)
    y = np.sin(x)
    plt.figure()
    plt.title(str(n+1))
    plt.plot(x,y)
```

returns:

![image](https://user-images.githubusercontent.com/3770323/56100336-1edb9080-5edd-11e9-9d77-60449185760b.png)
