### ISSUE TITLE
Correct Queries, Consistent Issues Running Database

### ISSUE THREAD

**Issue by abbywh** [jmbejara/comp-econ-sp19#60]
For every problem, I have the correct query when checked against the solutions. But, I consistently get errors when running the actual query on the database. Even if I copy and paste the solution code, it still won't run. Is it acceptable to turn in the code despite being unable to run it (knowing it's correct)? I've used SQL queries in kaggle before if it would make any difference for this one. 

EDIT: I think it's specifically with the first two and and/or any problem using a to_dataframe.

EDIT2: figured out the issue. For some reason you cannot always enter 1e9 for the safety insurance as it will pass as a float. Typing out the whole number will fix this.

**Comment by jmbejara** [comment]
Hi @jwhitty32 . For those with the same issue, I'm adding this link to redirect: https://github.com/jmbejara/comp-econ-sp19/issues/47
