### ISSUE TITLE
Kaggle Not Running

### ISSUE THREAD

**Issue by jbendelac** [jmbejara/comp-econ-sp19#62]
Hello, I'm having tons of troubles with Kaggle in multiple of the exercises. The first part of Joining Data for example, does not run successfully, even if I input the given "correct answer." How do I handle this/will we be graded on these if the exercises clearly are not working correctly? Thanks!

**Comment by jmbejara** [comment]
Hi! Take a look at this issue and see if that resolves your problem. https://github.com/jmbejara/comp-econ-sp19/issues/47
