### ISSUE TITLE
Colab printing to PDF not displaying some outputs

### ISSUE THREAD

**Issue by rhuselid** [jmbejara/comp-econ-sp19#7]
when I print my notebook to pdf (everything has ran and looks right), some of the codeblock output does not show up or is cut off by the next block. Ideas why this may be and/or should I not worry about this since the ipynb is also being submitted? Thanks!

**Comment by jmbejara** [comment]
Hmm. I'm not sure. Could you post a screenshot of an example? (You can copy and paste the image directly into the textbox here on the GitHub issue tracker and it will include the image.) But, yeah, it's best just to submit the ipynb file.

**Comment by rhuselid** [comment]
Here are a few examples. Roughly 1/3 of the images/outputs are truncated or incorrect when converted to pdf.

<img width="403" alt="not working" src="https://user-images.githubusercontent.com/32854361/56100683-77ad2800-5ee1-11e9-9863-73898839f74c.PNG">
<img width="434" alt="racc" src="https://user-images.githubusercontent.com/32854361/56100684-7a0f8200-5ee1-11e9-840c-bcd129ddd159.PNG">
<img width="201" alt="prnt" src="https://user-images.githubusercontent.com/32854361/56100710-c8248580-5ee1-11e9-84ce-fc6c31dc70e2.PNG">

**Comment by jmbejara** [comment]
Weird. I'm not sure. This might be something that you can bring up with the Colab team. Here are their suggestions:

> For support or help using Colab, please submit questions tagged with google-colaboratory on StackOverflow.
> 
> For any product issues, you can either submit an issue or "Help" -> "Send Feedback" in Colab.

You can raise an issue on their GitHub issue tracker https://github.com/googlecolab/colabtools or you can send feedback directly in Colab.
