### ISSUE TITLE
HW1 Q7 [𝜇 𝟙] clarification

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#8]
Just want to make sure that in Q7, after the formulas for the analytical solutions, you said that "Note that  [𝜇  𝟙]  is an  𝑁×2  matrix." But I think the number of rows for [𝜇  𝟙]  is k rather than N. Which is the correct row number?

**Comment by jmbejara** [comment]
Sorry about that! I might have mixed up my notation. 𝜇 is a vector containing the expected mean of each asset. There are 5 assets in our case, so it's a 5 x 1 vector.
