### ISSUE TITLE
Submission channel

### ISSUE THREAD

**Issue by sicelyli** [jmbejara/comp-econ-sp19#9]
When I tried to submit hw1, I did:
1. Clicked the "Push" button in GitKraken
2. Upload the ipynb file to econ-21410/hw-sicelyli repository
I'm wondering that are these two steps both required for hw submission? Or is step 2 good enough? What's the result when I pushed my completed hw using GitKraken? Thank you!

**Comment by jmbejara** [comment]
One or the other should work. However, when you use the "push" option, you need to do the following things:

* Add the changed files to the staging area
* Commit the files (be sure to add a descriptive commit message first)
* Push the commits.

The "push" button only pushes commits. Files that you edit or create will not get pushed unless you commit them.
